### ISSUE TITLE
A BUG ? 

### ISSUE THREAD

**Issue by cyy1992** [IIPCVLAB/LCCNet#28]
https://github.com/IIPCVLAB/LCCNet/blob/ad4e2547ef485b8a808c58aa5075a6f514241a4a/utils.py#L112
 这行代码 应该是矩阵乘法， 但是在这里 是*  （逐元素的乘法）

**Comment by Alaric102** [comment]
Hello, i've got the same question. Is there any outcomes?
I have launched evaluation script with `use_prev_output = False` and `random_initial_pose = True`.  Thus, i didn't find difference between Init, Prediction and GT images. 
I have debugged this line and T*R does element-wise multiplication instead of matrix multiplication. Thus further decomposition into Rotation, Translation and Scale vectors gives Identity Rotation, Zero Translation vectors, but non-identity and non-zero scale transform. 
I have replaced it by T@R and projection have become as expected. In addition, Rotation and translation decomposition are no longer identity and zero vectors respectively and no scale part (identity)
